# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
# pr: none

pool:
  vmImage: 'macos-10.14'

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: PowerShell@2
  name: SetBuildVariables
  displayName: Set environment-related variables
  inputs:
    targetType: inline
    script: |
      switch ("$(MAPEnvName)") {
        'cvp-dev' { 
            $fastlaneBuildCommand = "fastlane appface_build_dev";
            $buildConfiguration = "Release_Dev";
            $buildType = "Dev" 
        }
        'cvp-stg' { 
            $fastlaneBuildCommand = "fastlane appface_build_stg";
            $buildConfiguration = "Release_Dev";
            $buildType = "Stg" 
        }
        'cvp-uat' { 
            $fastlaneBuildCommand = "fastlane appface_build_uat";
            $buildConfiguration = "Release_Dev";
            $buildType = "Uat" 
        }
        'cvp' { 
            $fastlaneBuildCommand = "fastlane appface_build_prod";
            $buildConfiguration = "Release_Dev";
            $buildType = "Prod" 
        }
        'pla-pit' {
            $fastlaneBuildCommand = "fastlane appface_build_prod";
            $buildConfiguration = "Release_Dev";
            $buildType = "Prod" 
        }
        'pla-mgr' {
            $fastlaneBuildCommand = "fastlane appface_build_prod";
            $buildConfiguration = "Release_Dev";
            $buildType = "Prod" 
        }
        'pla-dev' {
            $fastlaneBuildCommand = "fastlane appface_build_prod";
            $buildConfiguration = "Release_Dev";
            $buildType = "Prod" 
        }
        'pla-stg' {
            $fastlaneBuildCommand = "fastlane appface_build_dev";
            $buildConfiguration = "Release_Dev";
            $buildType = "Dev" 
        }
        'pla-uat' {
            $fastlaneBuildCommand = "fastlane appface_build_prod";
            $buildConfiguration = "Release_Dev";
            $buildType = "Prod" 
        }  
        'vst-dev' { 
            $fastlaneBuildCommand = "fastlane appface_build_dev";
            $buildConfiguration = "Release_Dev";
            $buildType = "Dev" 
        }
      }

      echo "##vso[task.setvariable variable=buildConfiguration;isOutput=true]$buildConfiguration"
      echo "##vso[task.setvariable variable=fastlaneBuildCommand;isOutput=true]$fastlaneBuildCommand"
      echo "##vso[task.setvariable variable=buildType;isOutput=true]$buildType"

- powershell: |
    Write-Host $(SetBuildVars.buildType)
    Write-Host $(SetBuildVars.buildConfiguration)
    Write-Host $(SetBuildVars.fastlaneBuildCommand)

- bash: |
    echo "$(Build.QueuedBy) - $(SetBuildVars.buildType) - $(SetBuildVars.buildConfiguration) - $(SetBuildVars.fastlaneBuildCommand)" >> $(Build.Repository.LocalPath)/build.txt

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.Repository.LocalPath)
    contents: 'build.txt'
    targetFolder: $(Build.ArtifactStagingDirectory)    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'build_artifact'
