trigger:
  branches:
    include:
      - master

pool:
  vmImage: "macOS-10.14"

variables:
  boolVar: true

jobs:
  - job: Run
    condition: in(variables['Build.Reason'], 'IndividualCI', 'Manual')
    strategy:
      maxParallel: 3
      matrix:
        dev:
          env: dev
          release: true
        stg:
          env: stg
          release: true
        uat:
          env: uat
          release: false
    variables:
      env: 'dev'
    steps:
      - checkout: none
      - bash: echo "stg"
        displayName: not in dev, uat
        condition: notIn(variables['env'], 'dev', 'uat')
      - bash: echo "dev/uat"
        displayName: in dev, uat
        condition: in(variables['env'], 'dev', 'uat')
      - bash: echo "Release"
        displayName: release true
        condition: eq(variables['release'], true)
      - bash: echo "Not release"
        displayName: release false
        condition: ne(variables['release'], false)
