trigger:
  branches:
    include:
      - master

pool:
  vmImage: "macOS-10.14"

variables:
  boolVar: true

jobs:
  - job: Run
    condition: in(variables['Build.Reason'], 'IndividualCI', 'Manual')
    variables:
      env: 'dev'
    steps:
      - checkout: none
      - task: colinsalmcorner.colinsalmcorner-buildtasksbeta.tag-build-task.tagBuildOrRelease@0
        displayName: 'Tag Build'
        type: Build
        inputs:
          tags: |
            tag1
            tag2
      - bash: echo "stg"
        displayName: not in dev, uat
        condition: notIn(variables['env'], 'dev', 'uat')
      - bash: echo "dev/uat"
        displayName: in dev, uat
        condition: in(variables['env'], 'dev', 'uat')
      - bash: echo "Release"
        displayName: release true
        condition: eq(variables['release'], true)
      - bash: echo "Not release"
        displayName: release false
        condition: ne(variables['release'], false)
