schedules:
- cron: "*/5 * * * * "
  displayName: Run every 5 minutes
  branches:
    include:
      - master
  always: true

pool:
  vmImage: "macOS-10.15"

variables:
  boolVar: true

jobs:
  - job: Run
    condition: in(variables['Build.Reason'], 'Schedule', 'IndividualCI', 'Manual')
    variables:
      env: 'dev'
    steps:
      - checkout: none
      - bash: echo $(testBranch)