trigger:
  branches:
    include:
      - master

pool:
  vmImage: "macOS-10.14"

variables:
  boolVar: true

jobs:
  - job: Run
    steps:
    - bash: brew install ruby@2.6.5
    - bash: ruby --version
    