trigger:
  branches:
    include:
      - master

pool:
  vmImage: "macOS-10.14"

variables:
  boolVar: hui

jobs:
  - job: Run
    condition: in(variables['Build.Reason'], 'IndividualCI', 'Manual')
    steps:
      - bash: echo "Good"
        condition: eq(variables.boolVar, true)
      - bash: echo "Bad"
        condition: eq(variables.boolVar, false)
      - bash: echo "WTF"
        condition: eq(variables.boolVar, 'true')
      - bash: echo "WTF2"
        condition: eq(variables.boolVar, 'false')
