trigger:
  branches:
    include:
      - master

pool:
  vmImage: "macOS-10.14"

variables:
  boolVar: true

jobs:
  - job: Run
    condition: in(variables['Build.Reason'], 'IndividualCI', 'Manual')
    strategy:
      maxParallel: 3
      matrix:
        dev:
          env: dev
          buildType: Release
          dexProtector_m: true
          sslPinning: false
        stg:
          env: stg
          buildType: Release
          dexProtector_m: true
          sslPinning: false
    variables:
      dexProtector: $(dexProtector_m)
    steps:
      - template: template.yml
        parameters:
          yesNo: ${{ variables.dexProtector }}
