trigger:
  branches:
    include:
      - master

pool:
  vmImage: "macOS-10.15"

variables:
  boolVar: true

jobs:
  - job: Run
    condition: in(variables['Build.Reason'], 'IndividualCI', 'Manual')
    variables:
      env: 'dev'
    steps:
      - checkout: none      
      - bash: ruby -v
      - bash: fastlane env
