trigger:
  branches:
    include:
      - master

pool:
  vmImage: "macOS-10.14"

variables:
  boolVar: true

jobs:
  - job: Run
    steps:
    - bash: gem list
    - bash: sudo gem install faraday --version 0.15.4
    - bash: gem list
    