trigger:
  branches:
    include:
      - master

pool:
  vmImage: "macOS-10.14"

variables:
  boolVar: true

jobs:
  - job: Run
    steps:
    - task: UseRubyVersion@0
      inputs:
        versionSpec: '2.6.5'
        addToPath: true
    - bash: ruby --version
    