trigger:
  branches:
    include:
      - master

pool:
  vmImage: "macOS-10.14"

jobs:
  - job: Run
    steps:
    - powershell: |
        $date, $buildCounter = "$(Build.BuildNumber)".Split(".")
        while ($buildCounter.Length -lt 2) {$buildCounter = "0" + $buildCounter}
        $buildNumber = "$date" + "$buildCounter"
        echo "##vso[task.setvariable variable=buildNumber;isOutput=true]$buildNumber"
      name: UpdateBuildNumber
      displayName: Update Build Number
    
    - bash: 
        bash echo $(UpdateBuildNumber.buildNumber)